# https://github.com/hadolint/hadolint
ignored:
  - DL3008 # warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
  - SC2086 # info: Double quote to prevent globbing and word splitting.
